services:
  pocketbase:
    image: 'ghcr.io/coollabsio/pocketbase:latest'
    environment:
      - SERVICE_URL_POCKETBASE_8080
    volumes:
      - 'pocketbase-data:/app/pb_data'
      - 'pocketbase-hooks:/app/pb_hooks'
      - './pb_migrations:/app/pb_migrations'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8080/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_POCKETBASE_INSTANCE_URL=${SERVICE_URL_POCKETBASE}
    environment:
      - NEXT_PUBLIC_POCKETBASE_INSTANCE_URL=${SERVICE_URL_POCKETBASE}
    depends_on:
      - pocketbase
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  pocketbase-data:
  pocketbase-hooks:
